[package]
name = "cecremote"
version = "0.2.0"
edition = "2018"

[dependencies]
cec_linux = {version="*", features=["poll"]}
sispm = "*"
ctrlc = "*"
libpulse-binding="*"

[profile.release]
lto = "fat"
codegen-units = 1
strip = "symbols"
#panic = "abort"
