[package]
name = "cecremote"
version = "0.3.0"
edition = "2021"

[dependencies]
cec_linux = {version="*", features=["poll"]}
sispm = "*"
ctrlc = "*"
pipewire = "*"

[profile.release]
lto = "fat"
codegen-units = 1
strip = "symbols"
#panic = "abort"
